language: java
install:
  - ls -la /usr/lib/jvm/
  - ls -la /usr/lib/jvm/java-8-oracle/
script: /usr/lib/jvm/java-6-openjdk-amd64/java -version

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
   - oraclejdk8
