language: java
install: true
script: mvn clean install -DprocessorIntegrationTest.toolchainsFile=etc/toolchains-travis-jenkins.xml

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
   - oraclejdk8
