language: java
pre-install:
  - ls -la /usr/lib/jvm/java-6-openjdk-amd64
install: true
script: mvn clean install -DprocessorIntegrationTest.toolchainsFile=etc/toolchains-travis-jenkins.xml

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
   - oraclejdk8
